[GuiController]
sideBg = "#161616"
screenMargin = 16
smallMargin = 8

[GuiTrace]
tagLeft = 96
messageLeft = 160

[GuiNametable]
addressLeft = 72
dataLeft = 144

[GuiMapping]
descLeft = 220

[GuiPatternTable]
lineLeft = 40
lineColumn = 32
lineHeight = 8
sliderMargin = 24
grid_thickness = 2.5

[WidgetTabBar]
plainColor = "#323232"

[WidgetSlideBar]
defaultWidth = 20
minHeight = 120
tabColor = "#484848"

[WidgetDocument]
leftMargin = 48

[WidgetCheckBox]
textLeft = 40

[WidgetButton]
textLeft = 40
