[GuiController]
sideBg = "#161616"
screenMargin = 24
smallMargin = 8

[GuiTrace]
tagLeft = 96
messageLeft = 160

[GuiMapping]
descLeft = 220

[GuiPatternTable]
lineColumn = 32
sliderMargin = 24

[WidgetTabBar]
plainColor = "#323232"

[WidgetSlideBar]
defaultWidth = 20
minHeight = 120
tabColor = "#484848"

[WidgetDocument]
leftMargin = 48
