[GuiController]
sideBg = "#161616"
screenMargin = 24

[GuiTrace]
tagLeft = 96
messageLeft = 160

[GuiMapping]
descLeft = 220

[GuiPatternTable]
margin = 8

[WidgetTabBar]
plainColor = "#323232"

[WidgetSlideBar]
defaultWidth = 20
minHeight = 120
tabColor = "#484848"

[WidgetDocument]
leftMargin = 48
