[Common]
leftMargin = 48

[GuiController]
sideBg = "#161616"
sideWidth = 600

[GuiTrace]
tagLeft = 96
messageLeft = 160

[GuiMapping]
descLeft = 220

[WidgetSlideBar]
defaultWidth = 20
minHeight = 120
tabColor = "#484848"
